### ISSUE TITLE
Update connectors to the version that has support for Pravega 0.4.0 RC5

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega-samples#167]
**Problem description**
In preparation of `0.4.0` release, update connector version to the artifacts that has the support for Pravega version [v0.4.0-rc5](https://github.com/pravega/pravega/releases/tag/v0.4.0-rc5). 

**Problem location**
build configuration

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
Closed via #173.
