### ISSUE TITLE
Building samples fails because LombokProcessor could not be initialized

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-samples#184]
Building with `gradlew installDist` fails with the following error:
```
pravega-samples/hadoop-connector-examples/src/main/java/io/pravega/example/spark/wordcount/WordCount.java:30: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.IllegalArgumentException: com.sun.tools.javac.api.ClientCodeWrapper$WrappedStandardJavaFileManager extends com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager implements javax.tools.StandardJavaFileManager
```

Environment: 
- openjdk version "10.0.2" 2018-07-17
- Ubuntu 18.04.2 LTS

**Comment by RaulGracia** [comment]
Thanks @claudiofahey, could you check if the problem persists with `jdk8`, please?

**Comment by claudiofahey** [comment]
This problem only occurs with JDK 10. JDK 8 appears to work ok.
Specifically, this runs correctly: `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ ./gradlew clean installDist`

**Comment by claudiofahey** [comment]
Are we interested in supporting JDK 10 for developing Pravega applications now?

**Comment by claudiofahey** [comment]
Only Java 8 is supported by pravega-samples. Closing issue.
