### ISSUE TITLE
Wrong class package in documentation for flink connnector

### ISSUE THREAD

**Issue by elizabethbain** [pravega/pravega-samples#190]
Change log description
 in the process of setting up an environment to submit a pravega flink writer through the flink UI, I found an error in the job submission documentation for word cout.  The referenced class had a mistake in the package portion of the name.

Purpose of the change
Fix the instructions to use the correct name for the class. 

What the code does
Readme documentation modified to show the correct package name for the submitted job

How to verify it
Inspection: check changed package name against actual package of the source and/or class

Signed-off-by: Elizabeth Bain elizabeth.bain@emc.com

**Comment by RaulGracia** [comment]
Closed via #189.
