### ISSUE TITLE
ClientFactory should be replaced with EventStreamClientFactory 

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega-samples#232]
**Problem description**

Following the code merge from #4417, commit `94482e51e5324075d0be8d9c81a3871faaa5ef32` for issue #4416 in pravega master branch, building of `pravega-client-samples` failed due to missing class file `io.pravega.client.ClientFactory`.

```
/root/work/github/pravega-samples/pravega-client-examples/src/main/java/io/pravega/example/noop/SimpleReader.java:13: error: cannot find symbol
import io.pravega.client.ClientFactory;
                        ^
  symbol:   class ClientFactory
  location: package io.pravega.client
15 errors
:pravega-client-examples:compileJava (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.813 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pravega-client-examples:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```
**Problem location**

`pravega/client/src/main/java/io/pravega/client/`

**Suggestions for an improvement**

All the files using `io.pravega.client.ClientFactory` should be replaced with `io.pravega.client.EventStreamClientFactory`.

**Comment by RaulGracia** [comment]
@SomeshJoshi19 This has been already fixed in the `dev` branch (the one we use for current development). If you want to test things related to 0.7, you have to checkout the `dev` branch of samples, there you should not see this problem.
