### ISSUE TITLE
The help text and the code don't match

### ISSUE THREAD

**Issue by Guangfeng-Xu** [pravega/pravega-samples#253]
**Problem description**
The help text in  `ConsoleWriter` says that we should use `WRITE_EVENT_RK <<{routingKey}>> , {event}` to write the `{event}` out to the Stream or the current Transaction using `{routingKey}`. However, according to the code, the correct operation should be `WRITE_EVENT_RK ({routingKey}) {event}`. The help and the code don't match.

**Problem location**
`io.pravega.example.consolerw.ConsoleWriter`

**Suggestions for an improvement**
Change the help text or the code.

**Comment by RaulGracia** [comment]
Closed via #255.
