### ISSUE TITLE
add batch reader to pravega-sample

### ISSUE THREAD

**Issue by ravibeta** [pravega/pravega-samples#258]
### What This Change Is For
This issue is for demonstrating batch read with tls configuration. This particular case was found to be tricky on a Kubernetes deployment because it involved setting up the PravegaCluster with K8s services and tls which introduces a relay. On the other hand, this creates a standalone program that makes a direct tls connection to the Pravega server which makes it easier to use and rounds up the already popular secureWriter and secureReader.

### How to fix it
The certificate has to be valid. It is specified just like the test configuration for secure writer and reader. The former uses it for instantiating stream manager to create the scope and stream and write events to it while the latter reads it.  This client does a batch read. No additional changes is necessary to the batch reader. 

### How to verify the tls secured server can be used with longevity.
The controllerUri and the certificate mentioned have to match with the TLS secured PravegaServer. When the tls handshake is completed, the data and control plane activities will continue just like they did for a default configuration PravegaServer. It is better to try the certificate with curl against a secured standalone server  

### Normal Issue stuff:

- [x] Priority - low priority
- [x] Severity - low severity
- [x] Workaround - the tests are run without tls while a single test validates the tls configuration.

```
Done creating a client config.
Done creating batchClient for myscope/mystream
Done reading event by thread 22: hello secure world!
Done reading 1 events
Done reading ranges of size: 1
All done with reading! Exiting...
```

**Comment by RaulGracia** [comment]
Closed via #257.
