### ISSUE TITLE
Remove deprecated usage of PravegaSerialization

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega-samples#272]
`PravegaSerialization` is deprecated since `0.7` release, and Flink connector plans to remove this API now in https://github.com/pravega/flink-connectors/issues/439
 it's time now to remove the deprecated usages here: https://github.com/pravega/pravega-samples/search?q=pravegaserialization&type=

**Comment by RaulGracia** [comment]
Closed via #274.
