### ISSUE TITLE
Update dev branch to use flink-connectors 0.10.0 snapshot builds

### ISSUE THREAD

**Issue by thekingofcity** [pravega/pravega-samples#293]
**Problem description**
jcenter is being discontinued for public use and no more snapshots could be fetched.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

pravega-samples need to pull snapshot builds on dev branch during the development cycle.

ref: pravega/pravega#5984

**Problem location**
Build scripts

**Suggestions for an improvement**
One of potential alternatives for snapshot artifacts could be GitHub Packages Registry

**Comment by RaulGracia** [comment]
Closed via #294.
