### ISSUE TITLE
Add Python code examples in the Flink SQL samples

### ISSUE THREAD

**Issue by thekingofcity** [pravega/pravega-samples#295]
**Problem description**
The `pravega-flink-connector-sql-samples` in `scenarios` only supports the java version. Adding a python version would help those from other backgrounds.

**Problem location**
`pravega-flink-connector-sql-samples`

**Suggestions for an improvement**
https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/python/table_api_tutorial.html

**Comment by RaulGracia** [comment]
Closed via #296.
