### ISSUE TITLE
Update hyperlink that redirects to install and start Flink

### ISSUE THREAD

**Issue by kgh475926** [pravega/pravega-samples#297]
In `https://github.com/pravega/pravega-samples/blob/master/flink-connector-examples/doc/flink-wordcount/README.md`, under Run In Flink Environment, under Start Flink, the `here` hyperlink redirects to an old version of Flink. 

The `here` hyperlink needs to be updated to redirect to `https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/try-flink/local_installation/` or other proper version of flink.

**Comment by RaulGracia** [comment]
Closed via #298.
