### ISSUE TITLE
Use UTF8StringSerializer instead of JavaSerializer for better performance

### ISSUE THREAD

**Issue by thekingofcity** [pravega/pravega-samples#309]
**Problem description**
The existing `JavaSerializer` used in the writer and reader of several examples is slow and ineffieient. For all the String type serilization, we can use `UTF8StringSerializer` instead.
ref:
https://dzone.com/articles/avoiding-java-serialization
https://stackoverflow.com/questions/19447623/why-javas-serialization-slower-than-3rd-party-apis

**Problem location**
* scenarios\turbineheatsensor
* scenarios\turbineheatprocessor
* pravega-client-examples\gettingstarted
* pravega-client-examples\streamcuts
* pravega-client-examples\consolerw
* pravega-client-examples\secure

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
Closed via #310.
