### ISSUE TITLE
Add connectors as a source dependency

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-samples#69]
**Issue**
The Pravega samples are intended for end-users and thus depend on the latest binary release (e.g. 0.2.1). To also support co-development (where we update the samples to exercise an unreleased feature), a separate branch could point to a recent commit of Pravega rather than to a binary release.   I believe it makes sense to treat samples differently because _the source code is the final product_.

**Suggestions**
Let's introduce a new branch in the samples called `develop` which tracks the Pravega/connector master branch.  New sample code should be merged into `develop`.  In other words, let's follow the _gitflow_ approach ([ref](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)).

To ensure a stable build, let's use a source dependency, similar to pravega/flink-connectors#88.  On the develop branch, the submodule should point to a recent commit of the connector and of pravega.  It is vital that the Pravega commit-id be consistent with flink-connector and hadoop-connector.   Meanwhile, on the sample's master branch, the submodule will be ignored but (as a good practice) should point to the respective release branches.

**Comment by EronWright** [comment]
Ran into a serious complication with the composite build aspect; it appears to be impossible to depend on the _shaded_ connector library.   Seems we must use the old-fashioned way, i.e. a `GradleBuild` task to build the submodules.

**Comment by RaulGracia** [comment]
According to @vijikarthi, I proceed to close this issue.
