### ISSUE TITLE
Add sample(s) to illustrate the use of stream cuts

### ISSUE THREAD

**Issue by fpj** [pravega/pravega-samples#73]
We have the stream cut feature implemented in Pravega and we should have samples that illustrate how to use it.

**Comment by RaulGracia** [comment]
- [ ] Basic StreamCuts sample in `ConsoleReader`.
- [ ] Upgrade Pravega libraries and samples from 0.2.1 to 0.3.0.
- [ ] Create a more elaborated/independent sample app for StreamCuts.
