### ISSUE TITLE
`./gradlew installDist` hit  `Could not find io.pravega:hadoop-connectors:0.3.0-SNPASHOT

### ISSUE THREAD

**Issue by huide9** [pravega/pravega-samples#97]
...
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':hadoop-examples:compileClasspath'.
> Could not find io.pravega:hadoop-connectors:0.3.0-SNAPSHOT.
  Searched in the following locations:
      file:/home/hyin/.m2/repository/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      file:/home/hyin/.m2/repository/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      file:/home/hyin/.m2/repository/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
      https://jcenter.bintray.com/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      https://jcenter.bintray.com/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
      https://repo1.maven.org/maven2/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
      https://repository.apache.org/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      https://repository.apache.org/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      https://repository.apache.org/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
      https://oss.jfrog.org/artifactory/jfrog-dependencies/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/maven-metadata.xml
      https://oss.jfrog.org/artifactory/jfrog-dependencies/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.pom
      https://oss.jfrog.org/artifactory/jfrog-dependencies/io/pravega/hadoop-connectors/0.3.0-SNAPSHOT/hadoop-connectors-0.3.0-SNAPSHOT.jar
  Required by:
      project :hadoop-examples

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by RaulGracia** [comment]
Thanks @huide9 for your feedback. This is due to an incidental misconfiguration of `gradle.properties` in `master`branch. This will be fixed next week in our new release.
Meanwhile, you can try the samples from the `develop` branch which is working.

**Comment by RaulGracia** [comment]
Hi @huide9, we have done an important refactor of the repository (currently in `develop` branch).
I checked the following and it worked:
```
git clone -b develop https://github.com/pravega/pravega-samples
cd pravega-samples/
./gradlew installDist
```
I made sure of deleting my local maven repository for the `hadoop-connector` dependency and the one specified in the configuration has been downloaded:
```
ls ~/.m2/repository/io/pravega/pravega-connectors-hadoop/
0.3.0-17.a171316-SNAPSHOT  maven-metadata-local.xml
```
Please, let me know if it works for you as well.
Thanks!

**Comment by huide9** [comment]
no luck.
I followed  "Building Pravega Components from Source (Optional)"@ https://github.com/pravega/pravega-samples/blob/develop/README.md

`pravega` 
`flink-connectors'
`hadoop-connectors'   

are all `gradlew` scucceed, only 
$ git clone -b develop https://github.com/pravega/pravega-samples.git
$ cd pravega-samples
$ ./gradlew clean installDist
`pravega-sample` failed
$ git clone -b develop https://github.com/pravega/pravega-samples.git
$ cd pravega-samples
$ ./gradlew clean installDist_

screen log attached below:
---
Download https://jcenter.bintray.com/mx4j/mx4j/3.0.2/mx4j-3.0.2.jar
Download https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar
Download https://jcenter.bintray.com/org/apache/hadoop/hadoop-yarn-server-nodemanager/2.6.5/hadoop-yarn-server-nodemanager-2.6.5.jar

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':hadoop-connector-examples:compileClasspath'.
> Could not download pravega-connectors-hadoop.jar (io.pravega:pravega-connectors-hadoop:0.3.0-17.a171316-SNAPSHOT)
   > Could not get resource 'https://oss.jfrog.org/jfrog-dependencies/io/pravega/pravega-connectors-hadoop/0.3.0-17.a171316-SNAPSHOT/pravega-connectors-hadoop-0.3.0-17.a171316-20180602.141212-1.jar'.
      > Premature end of Content-Length delimited message body (expected: 23523399; received: 22958149

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 2s
16 actionable tasks: 10 executed, 6 up-to-date

**Comment by RaulGracia** [comment]
Hi @huide9,

I just tried the very same sequence of commands you posted and it worked for me. Apparently, the problem that you reported is related to the process of downloading the artifact itself (i.e., `Premature end of Content-Length`), which may be due to an actual problem in the artifact or a transient problem in the server serving the artifacts.

Can you confirm that this is still failing in your environment?

Thanks!

**Comment by huide9** [comment]
reinstalled ubuntu on a different machine and passed the build. 
followed the same procedure, nothing special!!!
the only thing I can guess is that I run this at Sunday afternnon when the network speed is pretty smooth compare to night time... possibly netowrk unstalbe?

anyway, thank you for your patience Raul.

--
Huide

**Comment by RaulGracia** [comment]
Happy that you could get it to work. I'll close the issue.
